name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 111.229.149.90
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          ssh_options: -o StrictHostKeyChecking=no
          script: |
            cd /www/wwwroot/jeep
            git pull